version: '3.8'
services:
  wildfly:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    volumes:
      - ./backend/src/main/webapp:/opt/jboss/wildfly/standalone/deployments
