version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080" #access port to the REST API
      - "4848:4848" #admin console port
    environment: #setting up mysql login credentials
      - MYSQL_URL=jdbc:mysql://LOCALHOST:3306/betterfb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql
    networks:
      - betterfb-network

  mysql:
    image: mysql:8.0
    environment: #setting up mysql login credentials
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: betterfb
    ports:
      - "3306:3306" #mysql port
    volumes: #making database files local for better testing
      - ./data/mysql:/var/lib/mysql
    networks:
      - betterfb-network

  #frontend:
  #  build:
  #    context: ./frontend
  #  ports:
  #    - "3000:3000"

networks:
  betterfb-network:
    driver: bridge
