version: '3.8'

services:
  wildfly:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    volumes:
      - ./backend/src/main/webapp:/opt/jboss/wildfly/standalone/deployments

  db:
    image: mysql:5.7
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Hasło dla użytkownika root
      MYSQL_DATABASE: my_database         # Nazwa bazy danych, która ma zostać utworzona
      MYSQL_USER: user                    # Użytkownik do połączenia
      MYSQL_PASSWORD: user_password       # Hasło dla nowego użytkownika
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql          # Użycie wolumenu do przechowywania danych